config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :experiences do
    resources :nibbles, only: [:create, :update, :destroy]
  end
  resources :users, only: [:edit, :update, :show, :destroy]
  get 'inbox', to: 'conversations#inbox', as: :inbox
  get 'inbox/:id', to: 'conversations#show', as: :conversation
  post 'inbox/:id/messages', to: 'messages#create', as: :new_message

  mount ActionCable.server => "/cable"

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages
  belongs_to :nibble

  validates :allowed, default: false, inclusion: { in: [true, false] }
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def inbox
    authorize current_user
    set_conversations
  end

  def show
    @conversation = Conversation.find(params[:id])
    mark_messages_as_read
    authorize @conversation
  end

  private

  def set_conversations
    @conversations = []
    Conversation.all.each do |conversation|
      if conversation.nibble.owner == current_user || conversation.nibble.interested == current_user
        @conversations << conversation
      end
    end
  end

  def mark_messages_as_read
    messages = @conversation.messages.where(recipient: current_user)
    messages.each { |message| message.read! }
  end
end

app/views/conversations/inbox.html.erb
<div class="container inbox-container">
  <h3 id="inbox-header">Your Messages</h3>
  <% @conversations.each do |conversation| %>
  <% who = conversation.nibble.interested == current_user ? conversation.nibble.owner : conversation.nibble.interested %>

  <div class="inbox-message">
    <div class="left-part-message">
      <div class="left-part-image">
      <%= cl_image_tag who.photos.first.picture,
      transformation: [{ height: 70, width: 70, crop: :thumb, gravity: :face}],
      style: "border-radius:50%;margin-left: 9px;height: 70px; object-fit:cover;",
      data: {toggle: "modal", target: "#user-modal"} %>
      </div>

      <div class="message-name">
        <h3><%= who.full_name %></h3>
        <p><%= link_to conversation.nibble.experience.title, conversation_path(conversation), style:"color:#333333" %></p>
      </div>
    </div>

    <% if conversation.messages.unread.where(recipient: current_user).length > 0  %>
      <span class="badge badge-primary" id="badge-message">
        <%= conversation.messages.unread.where(recipient: current_user).length %>
      </span>
    <% end %>


    <div class="right-part-message">
      <div class="message-body">
        <p>
          <%= link_to "#{conversation.messages.last.body[0..20]}...", conversation_path(conversation) %>
        </p>
        <div id="date"><%= conversation.messages.last.date %></div>
      </div>

      <div class="message-status">
        <p class="status <%= conversation.nibble.status %>" id="status_<%= conversation.nibble.id %> "><%= conversation.nibble.status.capitalize %></p>
        <%# if policy(conversation.nibble).update? && conversation.nibble.status == 'pending' %>
        <!-- <div id="status-buttons"> -->
          <%#= link_to '', experience_nibble_path(conversation.nibble.experience, conversation.nibble, status: 'accepted'),
          method: :patch, class: 'fas fa-check-circle', style: "color: #2E996E;margin: 0 10px;" %>
          <%#= link_to '', experience_nibble_path(conversation.nibble.experience, conversation.nibble, status: 'declined'),
          method: :patch, class: 'fas fa-thumbs-down', style: "color: #9B2E2E;" %>
        <!-- </div> -->
        <%# elsif !policy(conversation.nibble).update? && conversation.nibble.status == 'pending' %>
          <!-- <p><em>Patience is a virtue, right?</em></p> -->
        <%# end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/conversations/show.html.erb
<div class="all-message-content">

<div class="container">
  <div class="row flexbox-horizontal">
    <div class="col-sm-8">

      <% who = @conversation.nibble.interested == current_user ? @conversation.nibble.owner : @conversation.nibble.interested %>

      <div class="flexbox-vertical" style="margin:20px;">
      <!-- FROM HERE -->
      <div class="chat-header"><h4><%= @conversation.nibble.experience.title %> | <%= who.full_name %></h4></div>
      <div class="show-messages">
        <% @conversation.messages.sorted.each do |message| %>
          <%= render "messages/message", message: message, user_is_messages_author: message.sender == current_user %>
        <% end %>
      </div>
      <div id="create-message">
        <%= simple_form_for [@conversation, Message.new], url: new_message_path(@conversation), remote: true, html: {autocomplete: "off" } do |f| %>
          <%= f.input :sender_id, input_html: { value: current_user.id }, as: :hidden %>
          <%= f.input :body, label: false %>
          <%= f.submit "Send", class: 'btn btn-primary pull-right' %>
        <% end %>
        <div class="back-status-buttons">
          <%= link_to inbox_path do %>
            <i class="fas fa-chevron-left"></i> Back
          <% end %>
          <% if policy(@conversation.nibble).update? && @conversation.nibble.status == 'pending' %>
            <div class="accepted-declined">
              <%= link_to '', experience_nibble_path(@conversation.nibble.experience, @conversation.nibble, status: 'declined'),
              method: :patch, class: 'fas fa-times-circle', style: "color: #9B2E2E;margin: 0 10px;" %>
              <%= link_to '', experience_nibble_path(@conversation.nibble.experience, @conversation.nibble, status: 'accepted'),
              method: :patch, class: 'fas fa-check-circle', style: "color: #2E996E;" %>
            </div>
          <% else %>
            <p class="status <%= @conversation.nibble.status %>" id="status_<%= @conversation.nibble.id %> ">
              <%= @conversation.nibble.status.capitalize %>
            </p>
          <% end %>
          <div class="just"></div>
        </div>
      </div>
      <!-- TO HERE -->
      </div>
        <%#= render 'shared/date-modal' %>

    </div>
  </div>
</div>
<% content_for :after_js do %>
  <script>
    scrollLastMessageIntoView();
    App['conversation_<%= @conversation.id %>'] = App.cable.subscriptions.create(
      { channel: 'ConversationsChannel', conversation_id: <%= @conversation.id %> }, {
        received: (data) => {
          if (data.current_user_id !== <%= current_user.id %>) {
            messagesContainer = document.querySelector('.show-messages');
            messagesContainer.insertAdjacentHTML('beforeend', data.message_partial);
            scrollLastMessageIntoView();
          }
        }
      }
    )
    document.querySelector('html').scrollTop = 0;
  </script>
<% end %>

</div>