config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :experiences do
    resources :nibbles, only: [:create, :update, :destroy]
  end
  resources :users, only: [:edit, :update, :show, :destroy]
  get 'inbox', to: 'conversations#inbox', as: :inbox
  get 'inbox/:id', to: 'conversations#show', as: :conversation
  post 'inbox/:id/messages', to: 'messages#create', as: :new_message

  mount ActionCable.server => "/cable"

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_card.html.erb
<a href='/experiences/<%= experience.id %>' style="text-decoration: none;">
<div class="card" data-effect="zoom">
  <figure  class="card__image">
    <%= cl_image_tag experience.photos.first.picture, alt: experience.title %>
  </figure>
  <div class="card__header">
  </div>
  <div class="card__body">
    <div class="black-bar">
      <p class="card__name"><%= experience.title %></p>
    </div>
    <p class="card__bio"></p>
  </div>
  <div class="card__footer black-bar">
    <p class="card__date"><%= experience.humanize_date %></p>
  </div>
</div>
</a>

app/views/shared/_category_filter_modal.html.erb
<div class='modal fade' id="category-filter-modal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content modal-padding modal-background">

    <h2 class="text-center">What are you into?</h2>


      <%= form_tag({}, {method: :get, enforce_utf8: browser.ie?}) do %>

      <div class="flexbox-horizontal">
      <!-- first column -->
        <div class="category-column">
          <% Experience::CATEGORIES.first(4).each do |category| %>
            <%= check_box_tag 'category[]', category, checked = @categories && @categories.include?(category)%>
            <%= category %> <br>
          <% end %>
        </div>

      <!-- second column -->
        <div class="category-column">
          <% Experience::CATEGORIES.slice(4, 4).each do |category| %>
            <%= check_box_tag 'category[]', category, checked = @categories && @categories.include?(category)%>
            <%= category %> <br>
          <% end %>
        </div>

      <!-- third column -->
        <div class="category-column">
          <% Experience::CATEGORIES.last(4).each do |category| %>
            <%= check_box_tag 'category[]', category, checked = @categories && @categories.include?(category)%>
            <%= category %> <br>
          <% end %>
        </div>

        </div>

        <!-- button to submit -->
        <div class="button-container">
        <%= submit_tag("filter", name: nil, class: 'btn btn-primary') %>
        </div>

      <% end %>

      <!-- button to clear -->
      <%= render 'shared/clear_filters' %>

    </div>
  </div>
</div>

app/views/shared/_date-modal.html.erb
<div id="date_modal_content">
  <div class="modal fade" id="date-modal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content date-modal-content modal-padding modal-background">
        <button data-dismiss="modal" class="close user-x-button">×</button>
        <div class="date-card">
          <div class="date-user-photos">
            <%= cl_image_tag @nibble.interested.photos.first.picture, class: 'avatar-show-page' %>
            <%= image_tag "heart.svg" %>
            <%= cl_image_tag @nibble.owner.photos.first.picture, class: 'avatar-show-page' %>
          </div>
          <div class="text-center">
            <h3>You've got a <span>date</span>!</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_date-nibbles.html.erb
  <% if experience.nibbles.present? %>
    <% experience.nibbles.each do |nibble| %>
      <div class="date-nibble">
        <%= cl_image_tag nibble.interested.photos.first.picture,
            transformation: [{ height: 70, width: 70, crop: :thumb, gravity: :face}],
            style: "border-radius:50%;",
            data: {toggle: "modal", target: "#user-modal"} %>
        <div class="date-nibble-name">
          <h4><%= nibble.interested.full_name %></h4>
        </div>
        <div class="date-nibble-buttons">
          <%= link_to "Inbox", conversation_path(nibble.conversations.first), class: 'btn btn-primary' %>
          <p><%= nibble.status.capitalize %></p>
          <% if nibble.status == 'pending' %>
            <%= link_to '', experience_nibble_path(nibble.experience, nibble, status: 'declined'),
                method: :patch, class: 'fas fa-times-circle', style: "color: #9B2E2E;margin: 0 10px;" %>
            <%= link_to '', experience_nibble_path(nibble.experience, nibble, status: 'accepted'),
                method: :patch, class: 'fas fa-check-circle', style: "color: #2E996E;" %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="no-nibbles">
      <h4>You've got no nibbles yet</h4>
    </div>
  <% end %>

app/views/shared/_date_modal.js.erb
document.getElementById("date_modal_content").html("<%= escape_javascript(render 'shared/date-modal') %>");
document.getElementById("#date-modal").modal('show');

app/views/shared/_experiences_carousel.html.erb
<div class="carousel">
  <% experiences.each do |experience| %>
    <div class="carousel-cell">
      <%= cl_image_tag experience.photos.first.picture, alt: experience.title %>
    </div>
  <% end %>
</div>

app/views/shared/_experiences_masonry.html.erb
<div class="grid">

  <% experiences.each do |experience| %>

    <!-- GRID ITEM -->
    <a href='/experiences/<%= experience.id %>' class="grid-item" data-effect="zoom">
      <!-- PHOTO -->
      <div class="grid-image-background">
        <div class="grid-image">
          <%= cl_image_tag experience.photos.first.picture, alt: experience.title %>
        </div>
        <div class="grid-avatar">
          <%= cl_image_tag experience.user.photos.first.picture %>
          <p><%= experience.user.first_name %></p>
        </div>
      </div>

      <!-- TEXT CONTAINER -->
      <div class="grid-text-container">

        <!-- TITLE -->
        <div class="grid-text-title">
          <%= experience.title %>
        </div>

        <!-- DATE -->
        <div class="grid-text-date">
          <%= experience.humanize_date_shorthand %>
        </div>

      </div>
    </a>

  <% end %>
</div>

<script>
  var $grid = $('.grid').masonry({
    itemSelector: '.grid-item',
    columnWidth: 5,
    fitWidth: true
  });

  $grid.imagesLoaded().progress( function() {
    $grid.masonry('layout');
  });
</script>

<!-- PREVIOUS SCRIPT -->
<!-- <script>
  $('.grid').masonry({
    itemSelector: '.grid-item',
    columnWidth: 5,
    fitWidth: true
  });
</script>
 -->

app/views/shared/_false_front_new_experiences_form.html.erb
<div class="experiencesContainer" data-step="1" id="mainContainerForm">
  <div class="formSliderContainer" id="slider-new-experience">

    <div class="formContainer">
      <div class="create-form-flexbox">
        <i class="fas fa-angle-left left-side-arrow arrow-hide"></i>
        <div class="upper-form">
          <div class="form-group">
            <i class='fas fa-heart'></i>
            <i class="far fa-heart"></i>
           <i class="far fa-heart"></i>
            <h3>Name your date</h3>
            <input type="text" placeholder="Knitting a scarf for winter" id="input-1">
          </div>
          <div class="form-group">
            <h3>Select a category</h3>
            <div class="categories-container">

              <select id="input-2">
                <option id="intro-select">Select One</option>
              <% Experience::CATEGORIES.each do |category| %>
                <option id="selected-item" value="<%=category%>"><%=category%></option>
              <% end %>
              </select>

            </div>
          </div>
        </div>
        <!-- div class="button-container-form"> -->
          <!-- <div class="btn btn-primary muted"><</div> -->
          <i class="fas fa-angle-right right-side-arrow" id="new-date-1"></i>
        <!-- </div> -->
      </div>
    </div>
    <div class="formContainer">
      <div class="create-form-flexbox">
          <i class="fas fa-angle-left left-side-arrow" id="new-date-2-back"></i>
        <div class="upper-form">
          <div class="form-group">
            <i class='fas fa-heart'></i>
            <i class='fas fa-heart'></i>
           <i class="far fa-heart"></i>
            <h3>Upload a gorgeous photo</h3>
            <div class="create-form-image-flexbox">
              <div class="btn btn-primary btn-special-photo" id="photos-button">+</div>
              <div id="photo-file-name"></div>
            </div>
          </div>
          <div class="form-group">
            <h3>Add a short description</h3>
          <input type="text" placeholder="Winter is coming. Let’s knit together!" id="input-3">
          </div>
        </div>

          <i class="fas fa-angle-right right-side-arrow" id="new-date-2"></i>
      </div>
    </div>

    <div class="formContainer">
      <div class="create-form-flexbox">
            <i class="fas fa-angle-left left-side-arrow" id="new-date-3-back"></i>
        <div class="upper-form">
          <div class="form-group">
            <i class='fas fa-heart'></i>
            <i class='fas fa-heart'></i>
            <i class='fas fa-heart'></i>
            <h3>Pick a date</h3>
            <input placeholder="December 24, 2018" id="test-1" class="test-1 form-control string optional datepickr flatpickr-input input active" type="text">
          </div>
          <div class="form-group">
            <h3>Pick a location</h3>
            <input placeholder="Kreuzberg, Berlin" class="form-control string optional ap-input" type="text" name="experience[location]" id="input-4" autocomplete="off" spellcheck="false" role="combobox" aria-autocomplete="both" aria-expanded="false" aria-owns="algolia-places-listbox-0" dir="auto" style="position: relative; vertical-align:top;">
            <div class="flexbox-gofish-button">
              <div class="btn btn-primary" id="submit-experience-button">Go Fish!</div>
            </div>
          </div>
        </div>
        <i class="fas fa-angle-right right-side-arrow arrow-hide"></i>

            <div id="new-date-3"></div>

        </div>
      </div>
    </div>

        <div class="btn btn-primary" id="submit-experience-back">Back</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <!-- FOR LARGER SCREENS -->
  <div class="hidden-xs hidden-sm">

    <!-- USER SIGNED IN -->
    <% if user_signed_in? %>
      <% notif_message = current_user.received_messages.unread.length > 0 ? 'notification' : 'notification hidden' %>

      <div class="flexbox-horizontal">

        <!-- LEFT OF LOGO -->
        <%= link_to "EXPLORE", experiences_path, class: "item-padding item-margin link-item body-text" %>
        <%= link_to "CREATE", new_experience_path, class: "item-padding item-margin link-item body-text", style: "margin-right: 20px" %>

        <!-- LOGO -->
        <a href="/" class="navbar-logo center-text">
          <%= image_tag "logo.png", alt: "Date Fishing" %>
        </a>

        <!-- RIGHT OF LOGO -->
        <%= link_to "MESSAGES", inbox_path, class: "item-padding item-margin link-item body-text", style: "margin-left: 20px" %>
        <%= image_tag "heart.svg", class: notif_message, id: "message-notification" %>
        <%= link_to "PROFILE", user_path(current_user), class: "item-padding item-margin link-item body-text" %>
        <%= image_tag "heart.svg", class: 'notification hidden', id: "profile-notification" %>
    </div>

    <!-- USER NOT SIGNED IN -->
    <% else %>

      <div class="flexbox-horizontal">

        <%= link_to "EXPLORE", experiences_path, class: "item-padding item-margin link-item body-text" %>
        <%= link_to "RANDOM", experience_path(Experience.all.sample), class: "item-padding item-margin link-item body-text", style: "margin-right: 20px" %>

        <!-- LOGO -->
        <a href="/" class="navbar-logo center-text">
          <%= image_tag "logo.png", alt: "Date Fishing" %>
        </a>

        <!-- LOG IN -->
        <span class="item-padding item-margin link-item" data-toggle="modal" data-target="#log-in" style="margin-left: 20px">LOG IN</span>
        <%= render 'shared/log-in-modal' %>

        <!-- SIGN UP -->
        <span class="item-padding item-margin link-item" data-toggle="modal" data-target="#sign-up">SIGN UP</span>
        <%= render 'shared/sign-up-modal' %>

      </div>
    <% end %>
  </div>


  <!-- FOR SMALLER SCREENS -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Explore", experiences_path %></li>
          <li><%= link_to "Create", new_experience_path %></li>
          <li><%= link_to "Messages", inbox_path %></li>
          <li><a href="#">Profile</a><%#= link_to "Profile", user_path(current_user) %></li>
      </ul>
    </div>

  </div>
</div>

app/views/shared/_new_experience_modal_draft.html.erb
<div class='modal fade' id="new-experience" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content modal-padding modal-background">
      <h2>New Experience</h2>

      <%= simple_form_for(resource, as: resource_name, url: new_experience_path(resource_name)) do |f| %>
      <%= f.error_notification %>

      <div class="form-inputs">

      </div>

      <div class="form-actions">
        <%= f.button :submit, "Add Experience" %>
      </div>
      <% end %>

      <%= render "devise/shared/links" %>
    </div>
  </div>
</div>

<!-- Here's the link to the modal you will need in the navbar

    <div class="navbar-wagon-item navbar-wagon-link" data-toggle="modal" data-target="#new-experience">Create</div>
      <%= #render 'shared/new_experience_modal_draft' %>
-->

app/views/shared/_notification.html.erb
<%= image_tag "heart.svg", class: 'notification' %>

app/views/shared/_sign-up-modal.html.erb
<div class='modal fade' id="sign-up" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content sign-up-content-modal modal-padding modal-background">
      <button data-dismiss="modal" class="close">×</button>
      <h2>Sign Up</h2>

      <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { id: "signup-form-devise" }) do |f| %>
        <%= f.error_notification %>
        <div class="sign-up-form">
          <div class="form-inputs">
            <%= f.input :first_name %>
            <%= f.input :last_name %>
            <%#= f.input :birthday %>
            <%= f.input :birthday, as: :date, start_year: Date.today.year - 70, end_year: Date.today.year - 18 %>
            <%= f.input :gender, collection: User::GENDERS %>
            <%= f.input :seeking, collection: User::GENDERS %>
            <%= f.input :email,
            required: true,
            autofocus: true,
            input_html: { autocomplete: "email", id: "signup-email-field" }%>
            <%= f.input :password,
            required: true,
            hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
            input_html: { autocomplete: "new-password", id: "signup-password-field" } %>
            <%= f.input :password_confirmation,
            required: true,
            input_html: { autocomplete: "new-password", id: "signup-confirm-password-field" } %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Sign up", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>


    </div>
  </div>
</div>

app/views/shared/_user-profile-modal.html.erb
<div class="modal fade" id="user-modal" role="dialog">
  <div class="modal-dialog user-modal-dialog">
    <div class="modal-content user-modal-content modal-padding modal-background">
        <button data-dismiss="modal" class="close user-x-button">×</button>
        <div class="user-card">
        <div class="modal-image-container">
          <%= cl_image_tag @experience.user.photos.first.picture, class: 'modal-image' %>
        </div>

        <div class="user-card-name">
          <p> <strong><%= @experience.user.full_name %></strong>, <%= @experience.user.age %></p>
        </div>

        <div class="user-card-content">
          <%= content_tag :p, @experience.user.bio %>
        </div>
      </div>

    </div>
  </div>
</div>